### ISSUE TITLE
vcfcomp returns NAs

### ISSUE THREAD

**Issue by kiran-lee** [Zilong-Li/vcfppR#3]
Hi Zilong-Li,

Thank you for your software. I found it from your reply [here](https://github.com/rwdavies/STITCH/issues/95).

I am currently trying to use vcfcomp to test concordance between some imputed genotypes and their original genotypes using the following script:
library(vcfppR)
res <- vcfcomp(test = "x.vcf.gz", truth = "y.vcf.gz", region="z|z",  af="af.tsv", stats = "r2")
str(res)
write.table(res, file = "concordance", sep = "\t", col.names = T, row.names = T, quote = FALSE)

I used vcftools --freq to output the allele frequency for af.tsv.

However, this returns a dataframe fulls of NAs:
> str(res)
List of 2
 $ samples: chr [1:25] "/fastdata/bop21kgl/RawData/LIMS26076p5/Clean_aligned/418-2054_221014_L003__all_mapped_rehead.bam" "/fastdata/bop21$
 $ r2     : logi [1, 1:17] NA NA NA NA NA NA ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:17] "(0,1e-05]" "(1e-05,2e-05]" "(2e-05,5e-05]" "(5e-05,0.0001]" ...
> write.table(res, file = "concordance", sep = "\t", col.names = T, row.names = T, quote = FALSE)
>
> proc.time()
   user  system elapsed
190.199   5.955 196.606

Do you have a suggestion of where this is going wrong?

**Comment by Zilong-Li** [comment]
Hi Kiran,

I think the input region is not valid, which should be in the form of chr:start-end, or just chr. 

I'll add validators for the input in next release. Thanks for the feedback.

**Comment by Zilong-Li** [comment]
Also make sure the af.tsv is valid, which should have a header line and five columns. If the af is calculated from the truth file, you can just make vcfcomp doing the job by ignoring the af option ie af=NULL
