### ISSUE TITLE
Error: cannot allocate vector of size 12.2 Gb

### ISSUE THREAD

**Issue by Truongphikt** [Zilong-Li/vcfppR#4]
Hi, I'm excited to use this tool to evaluate my imputation results. But I bump into this error with my test cases even though I have run successfully with the repo's test set.

This is my R script:
```{R}
library(vcfppR)

rawvcf = "<path_to_file>/SAS-Axiom_JAPONICA_chr12_filterd.vcf.gz"
phasedvcf= "<path_to_file>/test_from_prs203/SAS_chr12_extract.vcf.gz"
maf_file = "<path_to_file>/test_from_prs203/12_maf.txt"

res <- vcfcomp(test = rawvcf, truth = phasedvcf,
               stats = "r2", 
               formats = c("GT","GT"))
               
# Save the plot to a PNG file
png(filename = "data_vcfplot_output.png", width = 800, height = 600)

par(mar=c(5,5,2,2), cex.lab = 2)
vcfplot(res, col = 2,cex = 2, lwd = 3, type = "b")

# Close the graphics device
dev.off()


png(filename = "data_phasing_output.png", width = 800, height = 600)
res <- vcfcomp(test = rawvcf, truth = phasedvcf,
               stats = "pse",
               return_pse_sites = TRUE)
#> stats F1 or NRC or PSE only uses GT format
vcfplot(res, which=1:2, main = "Phasing switch error", ylab = "HG00673,NA10840")
dev.off()
```

And I got the error at "phasing image" after waiting a while:
```
> 
> 
> png(filename = "data_phasing_output.png", width = 800, height = 600)
> res <- vcfcomp(test = rawvcf, truth = phasedvcf,
+                stats = "pse",
+                return_pse_sites = TRUE)
stats F1 or NRC or PSE only uses GT format
Error: cannot allocate vector of size 12.2 Gb
Execution halted
```

**Comment by Zilong-Li** [comment]
Thanks. Can you show me the machine  information and `sessionInfo()` ? Also, if you have limited memory, you may need to run `gc()` few times between many `vcfcomp()` calls to cut down peak RAM.

**Comment by Zilong-Li** [comment]
Another tip on using vcftable and vcfcomp, is setting info=false, which can save a lot of memory when the VCF has lots of annotation information in INFO field.

**Comment by Truongphikt** [comment]
Moreover, when I read [docs](https://cran.r-project.org/web/packages/vcfppR/vcfppR.pdf) at `vcfcomp`, I see the `af` argument.

> af &emsp; file path to allele frequency text file or saved RDS file.

Could you please give me more info about the "allele frequency text file" and "RDS" format?  Maybe It can help me use my "exterior MAF file" to overwrite MAF in true VCF. 

My "exterior MAF" format:
```
21:5030578:C:T	0.0115553
21:5030588:T:C	0.00827608
21:5030596:A:G	0.000312305
21:5030641:C:T	0
21:5030673:G:A	0.000312305
21:5030912:CA:C	0.00218613
21:5030957:G:A	0.037945
21:5030960:T:C	0.00374766
21:5031004:C:G	0.000312305
21:5031018:C:CCTATGATCA	0.000312305
```

**Comment by Zilong-Li** [comment]
You should use upper case as Boolean in R. Hence `info=FALSE`

**Comment by Truongphikt** [comment]
@Zilong-Li Do you have another solution for memory errors? When I try to run the repo's test set on all ranges in chr21 (tutorial is `chr21:1-5100000`) the error is still there, even though I granted 150.Gb for process.

**Comment by Zilong-Li** [comment]
Hey, did you read my recommendation on gc() ? This is a R memory thing that you have to learn how to manage. There is indeed another solution that avoids allocate all memory at the same time. Remind me if I forget to write a document on memory efficient usage for a long time.

**Comment by Truongphikt** [comment]
Sorry for not clearly saying. When I run my process, I only execute the `vcfcomp` function once, so `gc()` is irrelevant, isn't it? This is my command:
```
library(vcfppR)
res <- vcfcomp(test = "./20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.recalibrated_variants.vcf.gz", truth = "./1kGP_high_coverage_Illumina.chr21.filtered.SNV_INDEL_SV_phased_panel.vcf.gz", info=FALSE,
                 stats = "r2",
                 af="21_maf.txt",
                 bin=seq(0, 0.5, length.out = 20),
                 by.sample = FALSE,
                 by.variant = TRUE,
                 formats = c("GT","GT"),
                 )
write.csv(as.data.frame(res$r2), file = "none_chr21_snp-wise.csv", row.names = TRUE)
# Save the plot to a PNG file
png(filename = "none_chr21_snp-wise.png", width = 800, height = 600)
  
par(mar=c(5,5,2,2), cex.lab = 2)
vcfplot(res, col = 2,cex = 2, lwd = 3, type = "b")
dev.off()
```

Even when I use `gc()`, another error pops up (also related to memory):
```
  *** caught segfault ***
  address 0xc, cause 'memory not mapped'
  Error: no more error handlers available (recursive errors?); invoking 'abort' restart
  Execution halted
  Warning message:
  system call failed: Cannot allocate memory 
``` 

As far as I can see, these are a few memory error I met:
```
[E::bgzf_uncompress] Call to inflateInit2 failed: out of memory
  Error: std::bad_alloc
  Execution halted
```

```
Error: cannot allocate vector of size <...> Gb
  Execution halted
```

Thank you.
