### ISSUE TITLE
What is kind of evaluate matric of Peason R-square and NRC?

### ISSUE THREAD

**Issue by Truongphikt** [Zilong-Li/vcfppR#6]
Hi, vcfppR team,

I'm very grateful for the attempt to create a fast and convenient VCF evaluation tool. I had glimpsed through [the article][1] and [documentation][2] but still didn't know what kind of matric of Peason R-square was used. To my knowledge, usually, there are 2 kinds of approaches to calculating $r^2$:

- SNP-wise $r^2$ 
    - Step 1: Calculate Pearson at every variant 
    - Step 2: Calculate the mean of all Pearson $r^2$ in each MAF-bin
    
      ![image](https://github.com/user-attachments/assets/dd0b2f0c-86a8-4aa6-b237-76c766c155c1)

- Aggregated $r^2$
    -  Step 1: Collect all variants according to MAF value into a variety of MAF bins
    -  Step 2: Calculate Pearson correlation at each bin
    
       ![image](https://github.com/user-attachments/assets/325fd592-d26f-4613-b336-677a061761f5)

Does the `vcfppR` tool use either the above method or another one? I so desire to know. Thanks.

[1]: https://academic.oup.com/bioinformatics/article/40/2/btae049/7589925
[2]: https://cran.r-project.org/web/packages/vcfppR/vcfppR.pdf

**Comment by Zilong-Li** [comment]
Both are supported. Please refer to the doc of `vcfcomp`, particularly options `by.sample` and `by.variant`. Stay tuned. I will update the vignette and website at some point.

**Comment by Truongphikt** [comment]
@Zilong-Li Thanks for enthusiastic support. **Could you please tell me what is default value of `by.sample` and `by.variant` parameters?** This is what I guess what value should be set dependent on situation:

|                                 |   `by.sample`     |     `by.variant`    |
| ---------------------------- | ------------------------ | ------------------------ |
| Aggregated $r^2$ |          FALSE       |         FALSE        |
|  SNP-wise $r^2$    |          FALSE       |         TRUE         |
|   Aggregated NRC |          FALSE       |         FALSE       |
|   Sample-wise NRC |       TRUE          |         FALSE       |

**Is that correct?** I hope `vcfppR` becomes more widely used. Thanks.

**Comment by Zilong-Li** [comment]
You can find out the default arguments of a function in R by `args(vcfcomp)`. Also, here is the online docs https://zilong-li.github.io/vcfppR/reference/vcfcomp.html. Sorry, I am on vocation and can not update the docs and more details, but will do it after vocation. If you wish it being more popular, help spread it out by giving stars and forks of the repo. Thanks.

**Comment by Zilong-Li** [comment]
Hey, sorry for late reply. 

Your summarization on the `vcfcomp` is exactly correct. The default (`by.sample=FALSE` and `by.variant=FALSE`) will just aggregate everything for all samples in a bin of variants. If `by.sample` is TRUE, then calculate sample-wise statistics regardless the value of `by.sample`. If `by.sample=FALSE` and `by.variant=TRUE` and the number of samples is greater than 1, then calculate the SNP-wise statistics. 

Let me know if this helps.

Best,
Zilong
