### ISSUE TITLE
Reading dosages from VCF

### ISSUE THREAD

**Issue by GabrielHoffman** [Zilong-Li/vcfppR#7]
Thanks for the package!  

`vcfppR` and `vcfpp.h` makes it really easily to read VCFs into statistical analyses in `Rcpp`.  But it looks like only the 'GT' field is currently supported.  Since analysis of dosage values from imputed variants is a major use case for VCFs, do you think you can incorporate reading the "DS" field, when a `vector<double>` is passed to `BcfRecord.getGenotypes()`?

This would be a valuable contribution and substantially increase the userbase.

Best,
Gabriel

**Comment by Zilong-Li** [comment]
Thanks for the kind words. 

Yes. The API `BcfRecord.getGenotypes()` is a special case of `BcfRecord.getFORMAT(tag, v)`, which is convenient for use.  The 'DS' and other formats are supported via `BcfRecord.getFORMAT`, see the [doc here](https://zilongli.org/proj/vcfpp/classvcfpp_1_1_bcf_record#aad2859755f5399ab3e0e8854e4b973ce). Likewise, there is `bcfreader$getFORMAT` in `vcfppR` package. 

Let me know if this helps

Thanks.
Zilong

**Comment by GabrielHoffman** [comment]
Thanks.  `getFORMAT()` works, I just wasn't able to figure that out from the documentation

Best,
Gabriel
