### ISSUE TITLE
Crash when trying to read file with no tabix index

### ISSUE THREAD

**Issue by GabrielHoffman** [Zilong-Li/vcfppR#9]
Here is a minimal reproducible example when I query a VCF file without a tabix index.

```r
packageVersion("vcfppR") # 0.5.1
library(Rcpp)

# Set paths for compiler 
inclPath = "/Users/gabrielhoffman/workspace/repos/vcfppR/"
includeString = paste0("-I", inclPath, c("src/", "src/htslib-1.19.1/"), collapse=' ')
Sys.setenv("PKG_CXXFLAGS"=includeString)

# set library paths for compiler
libs = paste(paste0(.libPaths()[1], "/Rhtslib/usrlib/libhts.a"), "-lcurl -lz -lm -lbz2 -llzma ")
Sys.setenv("PKG_LIBS"=libs)

# minumal c++ function
# count the number of variants in a region
cppFunction('
#include "vcfpp.h"

using namespace vcfpp;
 
// [[Rcpp::export]]
int testFun(const std::string &file, const std::string &region) {
  
	BcfReader reader( file, region);
	int nVariants = 234;

	return nVariants;
}', depends="vcfppR")

# path to VCF
# NOTE: there is no tabix index with the version installed with the package
file <- system.file("extdata", "imputed.gt.vcf.gz", package="vcfppR")

# query valid region
testFun(file, "chr21:5030082-5030253")
```

The function correctly throws an error saying it can't find the index.

```r
[E::idx_find_and_load] Could not retrieve index file for '/Users/gabrielhoffman/prog/R-4.4.0/library/vcfppR/extdata/imputed.gt.vcf.gz'

 *** caught segfault ***
address 0x18, cause 'invalid permissions'

Traceback:
 1: .Call(<pointer: 0x103efd674>, file, region)
 2: testFun(file, "chr21:5030082-5030253")
```

I get the same error on 

OSX R 4.4.0
Ubuntu R 4.3.3
tested with both vcfppR 0.5.0 and 0.5.1

Best,
Gabriel

**Comment by GabrielHoffman** [comment]
This comes up because a fresh install using `remotes::install_github("Zilong-Li/vcfppR", force=TRUE)` produces the following files in the `extdata/` directory. 

```
imputed.gt.vcf.gz  raw.gt.vcf.gz      sv.vcf.gz
obj_vcfcomp.rds    raw.gt.vcf.gz.csi  sv.vcf.gz.csi
```

Can you include the index for `imputed.gt.vcf.gz`?

**Comment by Zilong-Li** [comment]
Hmmm, this is really odd. It works on my machines and all unit [tests](https://github.com/Zilong-Li/vcfppR/actions/runs/10989137966/job/30506764558)  passed though. 

The below is from my machine. 

![image](https://github.com/user-attachments/assets/08ee3771-842f-4fdd-bc17-9bedaedaa3b5)

**Comment by Zilong-Li** [comment]
> This comes up because a fresh install using `remotes::install_github("Zilong-Li/vcfppR", force=TRUE)` produces the following files in the `extdata/` directory.
> 
> ```
> imputed.gt.vcf.gz  raw.gt.vcf.gz      sv.vcf.gz
> obj_vcfcomp.rds    raw.gt.vcf.gz.csi  sv.vcf.gz.csi
> ```
> 
> Can you include the index for `imputed.gt.vcf.gz`?

The file without index is made on purpose for testing and capturing errors. Maybe you can use the file `raw.gt.vcf.gz`  for other purposes instead?
